GroupProject/Models/Sensor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GroupProject.Models
{
    public class Sensor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
    }
}

GroupProject/Controllers/Admin/SensorController.cs
using GroupProject.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GroupProject.Controllers.Admin
{
    public class SensorController : Controller
    {
        //mysql connection string
        private string connectionString = ConfigurationManager.ConnectionStrings["MySqlConnectionString"].ConnectionString;

        // GET: /Sensor/GetSensors
        [HttpGet]
        public JsonResult GetSensors(string searchQuery)
        {
            List<Sensor> sensors = new List<Sensor>();
            try
            {
                //GetSensors  mehtod
                using (MySqlConnection conn = new MySqlConnection(connectionString))
                {
                    conn.Open();
                    // Start the base query
                    string query = "SELECT * FROM Sensor WHERE 1=1";

                    // Filter by search query (location)
                    if (!string.IsNullOrEmpty(searchQuery))
                    {
                        query += " AND location LIKE @SearchQuery";
                    }

                    // Create the MySQL command with the query
                    using (MySqlCommand cmd = new MySqlCommand(query, conn))
                    {
                        // Only add the parameter if the search query is provided
                        if (!string.IsNullOrEmpty(searchQuery))
                        {
                            cmd.Parameters.AddWithValue("@SearchQuery", "%" + searchQuery + "%");
                        }

                        // Execute the query and read the results
                        MySqlDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            sensors.Add(new Sensor
                            {
                                Id = Convert.ToInt32(reader["id"]),
                                Name = reader["name"].ToString(),
                                Location = reader["location"].ToString(),
                                Status = reader["sensorStatus"].ToString(),
                                Latitude = reader.IsDBNull(reader.GetOrdinal("latitude")) ? 0f : (float)Convert.ToDouble(reader["latitude"]),
                                Longitude = reader.IsDBNull(reader.GetOrdinal("longitude")) ? 0f : (float)Convert.ToDouble(reader["longitude"]),
                                

                            });
                        }
                    }
                }
                return Json(sensors, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }





        [HttpPost]
        public JsonResult AddSensor(Sensor sensor)
        {
            try
            {
                
                using (MySqlConnection conn = new MySqlConnection(connectionString))
                {
                    conn.Open();
                    string query = "INSERT INTO sensor (location, sensorStatus, latitude, longitude, name) VALUES (@Location, @Status, @Latitude, @Longitude, @Name)";
                    using (MySqlCommand cmd = new MySqlCommand(query, conn))
                    {
                        cmd.Parameters.AddWithValue("@Name", sensor.Name);
                        cmd.Parameters.AddWithValue("@Location", sensor.Location);
                        cmd.Parameters.AddWithValue("@Status", sensor.Status);
                        cmd.Parameters.AddWithValue("@Latitude", sensor.Latitude);
                        cmd.Parameters.AddWithValue("@Longitude", sensor.Longitude);
                        
                        cmd.ExecuteNonQuery();
                    }
                }
                return Json(new { success = true, message = "Sensor added successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Error: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }




        // POST: /Sensor/UpdateSensor
        [HttpPost]
        public JsonResult UpdateSensor(Sensor updatedSensor)
        {
            //UpdateSensor method
            try
            {

                // Log the incoming sensor data for debugging
                System.Diagnostics.Debug.WriteLine($"Updating sensor with ID: {updatedSensor.Id}, Name: {updatedSensor.Name}, Location: {updatedSensor.Location}, Status: {updatedSensor.Status}");

                using (MySqlConnection conn = new MySqlConnection(connectionString))
                {
                    conn.Open();

                    // SQL query to update the sensor
                    string query = "UPDATE sensor SET name = @Name, location = @Location, sensorStatus = @Status, latitude = @Latitude, longitude = @Longitude WHERE id = @Id";
                    Console.WriteLine("Updating sensor with ID: " + updatedSensor.Id);
                    using (MySqlCommand cmd = new MySqlCommand(query, conn))
                    {
                        // Add parameters to avoid SQL injection
                        cmd.Parameters.AddWithValue("@Id", updatedSensor.Id);
                        cmd.Parameters.AddWithValue("@Name", updatedSensor.Name);
                        cmd.Parameters.AddWithValue("@Location", updatedSensor.Location);
                        cmd.Parameters.AddWithValue("@Status", updatedSensor.Status);
                        cmd.Parameters.AddWithValue("@Latitude", updatedSensor.Latitude);
                        cmd.Parameters.AddWithValue("@Longitude", updatedSensor.Longitude);


                        // Execute the query and log the number of affected rows
                        int rowsAffected = cmd.ExecuteNonQuery();
                        // Log how many rows are updated
                        System.Diagnostics.Debug.WriteLine($"Rows affected: {rowsAffected}");
                    }
                }
                // Return success if update is successful
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Return error message if an exception occurs
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }




        // POST: /Sensor/DeleteSensor
        [HttpPost]
        public JsonResult DeleteSensor(int id)
        {
            //Delete Sensor Method
            try
            {
                using (MySqlConnection conn = new MySqlConnection(connectionString))
                {
                    conn.Open();

                    // Delete records from airqualityhistory where sensor_id matches the one being deleted
                    string deleteHistoryQuery = "DELETE FROM airqualityhistory WHERE sensor_id = @Id";
                    using (MySqlCommand cmd = new MySqlCommand(deleteHistoryQuery, conn))
                    {
                        cmd.Parameters.AddWithValue("@Id", id);
                        // Delete related records in airqualityhistory
                        cmd.ExecuteNonQuery();  
                    }

                    // delete the sensor from the Sensor table
                    string deleteSensorQuery = "DELETE FROM Sensor WHERE id = @Id";
                    using (MySqlCommand cmd = new MySqlCommand(deleteSensorQuery, conn))
                    {
                        cmd.Parameters.AddWithValue("@Id", id);
                        cmd.ExecuteNonQuery();  // Delete the sensor
                    }

                }

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        //function to see if all sensors active 
        [HttpGet]
        public JsonResult GetSensorStatus(bool checkForActive = false)
        {
            List<SensorStatusModel> sensors = new List<SensorStatusModel>();
            int statusCount = 0;

            try
            {
                using (MySqlConnection conn = new MySqlConnection(connectionString))
                {
                    conn.Open();
                    string query = "SELECT sensorStatus FROM Sensor";

                    using (MySqlCommand cmd = new MySqlCommand(query, conn))
                    {
                        using (MySqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                var sensorStatus = new SensorStatusModel
                                {
                                    Status = reader["sensorStatus"].ToString()
                                };

                                sensors.Add(sensorStatus);

                                // Count how many sensors are 'active' or 'inactive' based on checkForActive flag
                                if (checkForActive)
                                {
                                    if (sensorStatus.Status.ToLower() == "active")
                                    {
                                        statusCount++;
                                    }
                                }
                                else
                                {
                                    if (sensorStatus.Status.ToLower() == "inactive")
                                    {
                                        statusCount++;
                                    }
                                }
                            }
                        }
                    }

GroupProject/Controllers/Admin/UserManagementController.cs
using GroupProject.Models;
using MySql.Data.MySqlClient;
using Org.BouncyCastle.Crypto.Generators;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GroupProject.Controllers.Admin
{
    public class UserManagementController : Controller
    {
        //mysql connection string
        private string connectionString = ConfigurationManager.ConnectionStrings["MySqlConnectionString"].ConnectionString;

        //Get method to get all users 
        [HttpGet]
        public JsonResult GetUsers(string userType, string searchQuery)
        {
            //create a list to store users
            List<User>users = new List<User>();
            try
            {
                using (MySqlConnection conn = new MySqlConnection(connectionString))
                {
                    //open connection
                    conn.Open();

                    //sql query
                    string query = "SELECT * FROM user WHERE 1=1";

                    //Filter by user type if not "ALL"
                    if (!string.IsNullOrEmpty(userType) && userType != "All")
                    {
                        query += " AND role = @Role";
                    }
                    //Filter by search query
                    if (!string.IsNullOrEmpty(searchQuery))
                    {
                        query += " AND LOWER(name) LIKE LOWER(@SearchQuery)";
                    }

                    using (MySqlCommand cmd = new MySqlCommand(query, conn))
                    {
                        //check for conditions
                        if (userType != "All")
                        {
                            cmd.Parameters.AddWithValue("@Role", userType);
                        }
                        if (!string.IsNullOrEmpty(searchQuery))
                        {
                            cmd.Parameters.AddWithValue("@SearchQuery", "%" + searchQuery + "%");
                        }
                        MySqlDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            //add data to the list
                            users.Add(new User
                            {
                                Id = Convert.ToInt32(reader["id"]),
                                Name = reader["name"].ToString(),
                                Role = reader["role"].ToString(),
                                Email = reader["email"].ToString(),
                                Password = reader["password"].ToString(),
                                Status = reader["status"].ToString()
                            });
                        }
                        return Json(users, JsonRequestBehavior.AllowGet);

                    }
                }
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        //method to check whether 
        [HttpGet]
        public JsonResult CheckUserName(string name)
        {
            //variable to see if the name exists
            bool exists = false;
            try
            {
                using(MySqlConnection  conn = new MySqlConnection(connectionString))
                {
                    //open conn
                    conn.Open();
                    string query  = "SELECT COUNT(*) FROM user WHERE name = @Name";
                    using (MySqlCommand cmd = new MySqlCommand(query, conn))
                    {
                        cmd.Parameters.AddWithValue("@Name", name);
                        int count = Convert.ToInt32(cmd.ExecuteScalar());
                        exists = count > 0;
                    }
                }

            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(exists, JsonRequestBehavior.AllowGet);
        }

        //Post method to create a new admin user
        [HttpPost]
        public JsonResult AddAdmin(string name, string email, string password, string role, string status)
        {

            try
            {
                string hashedPassword = BCrypt.Net.BCrypt.HashPassword(password);
                using (MySqlConnection con = new MySqlConnection(connectionString))
                {
                    //open connection
                    con.Open();
                    // SQL to insert new user
                    string query = "INSERT INTO user (name, email, password, role, status) VALUES (@Name, @Email, @Password, @Role, @Status)";
                    using(MySqlCommand cmd = new MySqlCommand( query, con))
                    {
                        //set data
                        cmd.Parameters.AddWithValue("@Name", name);
                        cmd.Parameters.AddWithValue("@Email", email);
                        cmd.Parameters.AddWithValue("@Password", hashedPassword);
                        cmd.Parameters.AddWithValue("@Role", role);  
                        cmd.Parameters.AddWithValue("@Status", status);
                        int result = cmd.ExecuteNonQuery();

                        if (result > 0)
                        {
                            return Json(new { success = true });
                        }
                        else
                        {
                            return Json(new { success = false, error = "Failed to create user." });
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = ex.Message });
            }
        }

        //user status updated 
        [HttpPost]
        public JsonResult UpdateUserStatus(int userId, string status)
        {
            try
            {
                using (MySqlConnection conn = new MySqlConnection(connectionString))
                {
                    conn.Open();
                    string query = "UPDATE user SET status = @Status WHERE id = @UserId";
                    using (MySqlCommand cmd = new MySqlCommand(query, conn))
                    {
                        cmd.Parameters.AddWithValue("@UserId", userId);
                        cmd.Parameters.AddWithValue("@Status", status);

                        int result = cmd.ExecuteNonQuery();

                        if (result > 0)
                        {
                            return Json(new { success = true });
                        }
                        else
                        {
                            return Json(new { success = false, message = "Failed to update user status." });
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

    }
}

GroupProject/Views/Admin/DashboardAdmin.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userRole = Session["UserRole"] as string;
}

<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Admin/DashboardAdminCss.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <!-- Link to the Sensors page -->
    <!--nav bar-->
    <nav class="navbar">
        <ul>
            <!-- Link visible to everyone -->
            <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>

            <!-- Links for Admin and SuperAdmin -->
            @if (userRole == "Admin" || userRole == "SuperAdmin")
            {
                <li>@Html.ActionLink("Dashboard For Admins", "DashboardAdmin", "Admin")</li>
                <li>@Html.ActionLink("Sensor Management", "Sensor", "Admin")</li>
            }

            <!-- Links only for SuperAdmin -->
            @if (userRole == "SuperAdmin")
            {
                <li>@Html.ActionLink("User Management", "UserManagement", "Admin")</li>
            }

            <!-- If user is logged in, show the logout link -->
            @if (Session["UserName"] != null)
            {
                <li>Welcome, @Session["UserName"]</li>
                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
            }
            else
            {
                <!-- If user is not logged in, show login/register links -->
                <li>@Html.ActionLink("Login", "LogIn", "Home")</li>
                <li>@Html.ActionLink("Register", "CreateAccount", "Home")</li>
            }
        </ul>
    </nav>
    <h1>Admin Page</h1>
    <!--End of nvabar-->
    <!--Body Section-->
    <!--Btn to stop data gen-->
    <button id="stopDataGen" type="button">Stop Data Generation</button>
    <!--Btn to start the data gen-->
    <button id="startDataGen" type="button">Start Data Generation</button>
    <!--Number of Sensors in the System-->
    <div class="card-container">
        <!--Active sensors-->
        <div class="sensor-card">
            <h4>Active Sensors</h4>
            <p id="activeSensors">Loading...</p>
        </div>
        <!--End of active sensors-->
        <!--Inactive sensors-->
        <div class="sensor-card">
            <h4>InActive Sensors</h4>
            <p id="inActiveSensors">Loading...</p>
        </div>
        <!--End of Sensor section-->
        <!--Number of Users-->
        <div class="sensor-card">
            <h4>Registered Users</h4>
            <p id="totalUsers">Loading...</p>
        </div>
        <div class="sensor-card">
            <h4>Admin Accounts</h4>
            <p id="adminAcc">Loading...</p>
        </div>
    </div>
    <!-- Graph Section: Bar Chart for Active/Inactive Sensors -->
    <div>
        <h4>Sensor Status Chart</h4>
        <canvas id="sensorChart" width="150" height="50"></canvas>
    </div>
    <!--End of User Section-->
    <!--Graph Section-->
    <!--End of Graph Section-->
    <!--End of body section-->
    <!-- Footer -->
    <!--End of Footer-->
    <!--JS section-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!--chart JS libray-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- Link to the separate JS file -->
    <script src="~/Scripts/Admin/Adminfeatures.js"></script>
    <!--End of js section-->
</body>
</html>

GroupProject/Views/Admin/UserManagement.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userRole = Session["UserRole"] as string;
}

<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/UserManagementCss.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <!--nav bar-->
    <nav class="navbar">
        <ul>
            <!-- Link visible to everyone -->
            <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>

            <!-- Links for Admin and SuperAdmin -->
            @if (userRole == "Admin" || userRole == "SuperAdmin")
            {
                <li>@Html.ActionLink("Dashboard For Admins", "DashboardAdmin", "Admin")</li>
                <li>@Html.ActionLink("Sensor Management", "Sensor", "Admin")</li>
            }

            <!-- Links only for SuperAdmin -->
            @if (userRole == "SuperAdmin")
            {
                <li>@Html.ActionLink("User Management", "UserManagement", "Admin")</li>
            }

            <!-- If user is logged in, show the logout link -->
            @if (Session["UserName"] != null)
            {
                <li>Welcome, @Session["UserName"]</li>
                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
            }
            else
            {
                <!-- If user is not logged in, show login/register links -->
                <li>@Html.ActionLink("Login", "LogIn", "Home")</li>
                <li>@Html.ActionLink("Register", "CreateAccount", "Home")</li>
            }
        </ul>
    </nav>
    <!--End of nvabar-->
    <div class="container">
        <h1>User Managment Page</h1>
        <!--Body-->
        <div class="user-filter">
            <!--User Role Filter-->
            <label for="userType">Select User Type: </label>
            <select id="userType" name="userType">
                <option value="All" selected>All Users</option>
                <option value="Admin">Admin</option>
                <option value="User">User</option>
            </select>


            <!--Serach Bar-->
            <label for="searchUser">Search User by Name: </label>
            <input type="text" id="searchUser" name="searchUser" placeholder="Enter User Name" />
            <button id="searchButton" type="button">Search</button>
        </div>

        <!--Dynamic Table-->
        <div class="container-flex">
            <table id="userTable" , border="1">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Rows will be dynamically added here -->
                </tbody>
            </table>

            <!--Add User Form-->
            <div id="userForm">
                <h3 id="formTitle">Add New User</h3>
                <form id="userFormData">
                    <label for="name">User Name: </label>
                    <input type="text" id="name" name="name" required />
                    <br />
                    <label for="email">User Email: </label>
                    <input type="email" id="email" name="email" required />
                    <br />
                    <label for="password">User Password: </label>
                    <input type="password" id="password" name="password" required />
                    <br />
                    <!-- Hidden fields for default Role and Status -->
                    <input type="hidden" id="role" name="role" value="Admin" />
                    <input type="hidden" id="status" name="status" value="Enter" />
                    <button id="submitUser" type="button">Submit</button>
                </form>

            </div>
        </div>
    </div>
    <!--End of Add User Form-->
    <!--End of Body-->
    <!--Footer-->
    <!--End of footer-->
    <!--JS section-->
    <!-- Include jQuery from CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.js"></script>
    <!-- Link to the separate JS file -->
    <script src="~/Scripts/Admin/userManagement.js"></script>
</body>
</html>

GroupProject/Views/Admin/sensor.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userRole = Session["UserRole"] as string;
}

<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Admin/sensorCss.css" rel="stylesheet" type="text/css" />

</head>
<body>

    <!--nav bar-->
    <nav class="navbar">
        <ul>
            <!-- Link visible to everyone -->
            <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>

            <!-- Links for Admin and SuperAdmin -->
            @if (userRole == "Admin" || userRole == "SuperAdmin")
            {
                <li>@Html.ActionLink("Dashboard For Admins", "DashboardAdmin", "Admin")</li>
                <li>@Html.ActionLink("Sensor Management", "Sensor", "Admin")</li>
            }

            <!-- Links only for SuperAdmin -->
            @if (userRole == "SuperAdmin")
            {
                <li>@Html.ActionLink("User Management", "UserManagement", "Admin")</li>
            }

            <!-- If user is logged in, show the logout link -->
            @if (Session["UserName"] != null)
            {
                <li>Welcome, @Session["UserName"]</li>
                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
            }
            else
            {
                <!-- If user is not logged in, show login/register links -->
                <li>@Html.ActionLink("Login", "LogIn", "Home")</li>
                <li>@Html.ActionLink("Register", "CreateAccount", "Home")</li>
            }
        </ul>
    </nav>
    <h1>Sensor Management</h1>
    <!--End of nvabar-->
    <!--Body Section-->
    <!--Search Bar to find sensor-->
    <div class="search-bar">
        <label for="searchSensor">Seach Sensor by Location</label>
        <input type="text" id="searchSensor" name="searchSensor" placeholder="Enter Sensor Loaction" />
        <button id="searchSensorBtn" type="button">Search</button>

    </div>
    <!--End of Search bar section-->
    <!--Dynamic Table to show Sensors-->
    <div class="container-flex">
        <table id="sensorTable" border="1">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Location</th>
                    <th>Status</th>
                    <th>Longitude</th>
                    <th>Latitude</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <!-- Rows will be dynamically created here -->
            </tbody>
        </table>

        <!--End of table section-->
        <!--Form For Add New and Edit Form -->
        <div id="sensorForm">
            <h3 id="formTitle" class="newSensor">Add New Sensor</h3>
            <button id="backToAddNew" type="button" style="display:none;">Back to Add New</button>
            <form id="sensorFormData">
                <label for="name">Sensor Name: </label>
                <input type="text" id="name" name="name" required />
                <br />
                <label for="location">Sensor Location: </label>
                <input type="text" id="location" name="location" required />
                <br />
                <label for="latitude">Sensor Latitude: </label>
                <input type="text" id="latitude" name="latitude" required />
                <br />
                <label for="longitude">Sensor Longitude: </label>
                <input type="text" id="longitude" name="longitude" required />
                <br />
                <label for="status">Status: </label>
                <select id="status" name="status">
                    <option value="Active">Active</option>
                    <option value="Inactive">Inactive</option>
                </select>
                <br />
                <button id="submitSensor" type="button">Submit</button>
            </form>
        </div>
    </div>
    <!--End of Form-->
    <!--End of Body Section-->
    <!--Footer-->
    <!--End of Footer-->
    <!--JS section-->
    <!-- Include jQuery from CDN -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Link to the separate JS file -->
    <script src="~/Scripts/Admin/sensorManagement.js"></script>

</body>
</html>